In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("user_strengths.csv")

In [3]:
df.head()

user_id  strength_id_1  strength_id_2  strength_id_3  strength_id_4  \
0        1              8              5              2             17   
1       41              1              2              1              1   
2       51              0              0              1              2   
3      151              5              2              0              7   
4      161              0              0              1              1   

   strength_id_5  strength_id_6  strength_id_7  strength_id_8  
0              9             12              3              8  
1              1              1              1              1  
2              0              0              0              2  
3              1              2              1              4  
4              0              1              0              0

In [4]:
df.isnull().sum()

user_id          0
strength_id_1    0
strength_id_2    0
strength_id_3    0
strength_id_4    0
strength_id_5    0
strength_id_6    0
strength_id_7    0
strength_id_8    0
dtype: int64

In [5]:
for i in range(0,200):
    if print(df[df["strength_id_1"].values==i].iloc[:,0:2].values):
        pass
        

[[     51       0]
 [    161       0]
 [    311       0]
 ...
 [6344780       0]
 [6344794       0]
 [6344832       0]]
[[     41       1]
 [    211       1]
 [    331       1]
 ...
 [6344990       1]
 [6345087       1]
 [6345142       1]]
[[   1381       2]
 [   2451       2]
 [   6031       2]
 ...
 [6343711       2]
 [6343913       2]
 [6344345       2]]
[[    981       3]
 [   4521       3]
 [   4911       3]
 ...
 [6339994       3]
 [6341412       3]
 [6341925       3]]
[[    941       4]
 [   1881       4]
 [   5511       4]
 [   7741       4]
 [  11811       4]
 [  21780       4]
 [  23503       4]
 [  23967       4]
 [  24541       4]
 [  24895       4]
 [  25905       4]
 [  26275       4]
 [  28889       4]
 [  32864       4]
 [  36509       4]
 [  48227       4]
 [  51078       4]
 [  51913       4]
 [  57481       4]
 [  71077       4]
 [  76800       4]
 [  81374       4]
 [  87826       4]
 [ 116034       4]
 [ 168425       4]
 [ 182912       4]
 [ 233290       4]
 [ 2498

In [23]:
for i in range(200):
    if (df[df["strength_id_1"].values==i].iloc[:,0:2].values).any():
        df1=df[df["strength_id_1"].values==i].iloc[:,:2]
        

In [24]:
df1 #last element 

user_id  strength_id_1
2998  6286559            111

#### trying to draw same appproach as purpose one !!